[2024-08-09T13:27:40.484+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_api.analyze_data manual__2024-08-09T13:25:30.584850+00:00 [queued]>
[2024-08-09T13:27:40.488+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_api.analyze_data manual__2024-08-09T13:25:30.584850+00:00 [queued]>
[2024-08-09T13:27:40.488+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-08-09T13:27:40.497+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): analyze_data> on 2024-08-09 13:25:30.584850+00:00
[2024-08-09T13:27:40.502+0000] {standard_task_runner.py:57} INFO - Started process 4596 to run task
[2024-08-09T13:27:40.506+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_api', 'analyze_data', 'manual__2024-08-09T13:25:30.584850+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/spark-jobs.py', '--cfg-path', '/tmp/tmpt6wfewtf']
[2024-08-09T13:27:40.512+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask analyze_data
[2024-08-09T13:27:40.638+0000] {task_command.py:415} INFO - Running <TaskInstance: data_pipeline_api.analyze_data manual__2024-08-09T13:25:30.584850+00:00 [running]> on host 27ef58cc88fc
[2024-08-09T13:27:40.700+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_api' AIRFLOW_CTX_TASK_ID='analyze_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T13:25:30.584850+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-09T13:25:30.584850+00:00'
[2024-08-09T13:27:40.702+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-09T13:27:40.703+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash /opt/***/jobs/spark-submit.sh /opt/***/jobs/analyze_data.py ']
[2024-08-09T13:27:40.710+0000] {subprocess.py:86} INFO - Output:
[2024-08-09T13:27:40.713+0000] {subprocess.py:93} INFO - /opt/***/jobs/analyze_data.py
[2024-08-09T13:27:40.790+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-08-09T13:27:43.504+0000] {subprocess.py:93} INFO - 24/08/09 13:27:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-09T13:27:45.588+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO SparkContext: Running Spark version 3.5.1
[2024-08-09T13:27:45.593+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO SparkContext: OS info Linux, 6.6.32-linuxkit, aarch64
[2024-08-09T13:27:45.594+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO SparkContext: Java version 11.0.23
[2024-08-09T13:27:45.643+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO ResourceUtils: ==============================================================
[2024-08-09T13:27:45.645+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-08-09T13:27:45.646+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO ResourceUtils: ==============================================================
[2024-08-09T13:27:45.646+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO SparkContext: Submitted application: FinanceDataAnalysis
[2024-08-09T13:27:45.669+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 1024, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-08-09T13:27:45.678+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2024-08-09T13:27:45.679+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-08-09T13:27:45.775+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO SecurityManager: Changing view acls to: ***
[2024-08-09T13:27:45.776+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO SecurityManager: Changing modify acls to: ***
[2024-08-09T13:27:45.777+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO SecurityManager: Changing view acls groups to:
[2024-08-09T13:27:45.777+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO SecurityManager: Changing modify acls groups to:
[2024-08-09T13:27:45.777+0000] {subprocess.py:93} INFO - 24/08/09 13:27:45 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-08-09T13:27:46.153+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO Utils: Successfully started service 'sparkDriver' on port 34925.
[2024-08-09T13:27:46.320+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO SparkEnv: Registering MapOutputTracker
[2024-08-09T13:27:46.400+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO SparkEnv: Registering BlockManagerMaster
[2024-08-09T13:27:46.425+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-08-09T13:27:46.432+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-08-09T13:27:46.435+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-08-09T13:27:46.497+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-51fc1150-79e7-43e3-9485-fd0279a976cb
[2024-08-09T13:27:46.526+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO MemoryStore: MemoryStore started with capacity 1458.4 MiB
[2024-08-09T13:27:46.547+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-08-09T13:27:46.708+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-08-09T13:27:46.771+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-08-09T13:27:46.779+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2024-08-09T13:27:46.836+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO SparkContext: Added JAR file:///opt/bitnami/spark/resources/elasticsearch-spark-30_2.12-8.4.3.jar at spark://27ef58cc88fc:34925/jars/elasticsearch-spark-30_2.12-8.4.3.jar with timestamp 1723210065537
[2024-08-09T13:27:46.912+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-08-09T13:27:46.949+0000] {subprocess.py:93} INFO - 24/08/09 13:27:46 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.4:7077 after 18 ms (0 ms spent in bootstraps)
[2024-08-09T13:27:47.053+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240809132747-0017
[2024-08-09T13:27:47.061+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34071.
[2024-08-09T13:27:47.062+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO NettyBlockTransferService: Server created on 27ef58cc88fc:34071
[2024-08-09T13:27:47.063+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-08-09T13:27:47.067+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 27ef58cc88fc, 34071, None)
[2024-08-09T13:27:47.070+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO BlockManagerMasterEndpoint: Registering block manager 27ef58cc88fc:34071 with 1458.4 MiB RAM, BlockManagerId(driver, 27ef58cc88fc, 34071, None)
[2024-08-09T13:27:47.071+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 27ef58cc88fc, 34071, None)
[2024-08-09T13:27:47.075+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 27ef58cc88fc, 34071, None)
[2024-08-09T13:27:47.237+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-08-09T13:27:47.540+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-08-09T13:27:47.546+0000] {subprocess.py:93} INFO - 24/08/09 13:27:47 INFO SharedState: Warehouse path is 'file:/tmp/***tmpw09bjyg9/spark-warehouse'.
[2024-08-09T13:27:48.519+0000] {subprocess.py:93} INFO - 24/08/09 13:27:48 INFO Version: Elasticsearch Hadoop v8.4.3 [a7873eb469]
[2024-08-09T13:27:48.688+0000] {subprocess.py:93} INFO - 24/08/09 13:27:48 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240809132747-0017/0 on worker-20240809124721-172.18.0.6-35359 (172.18.0.6:35359) with 1 core(s)
[2024-08-09T13:27:48.695+0000] {subprocess.py:93} INFO - 24/08/09 13:27:48 INFO StandaloneSchedulerBackend: Granted executor ID app-20240809132747-0017/0 on hostPort 172.18.0.6:35359 with 1 core(s), 1024.0 MiB RAM
[2024-08-09T13:27:48.697+0000] {subprocess.py:93} INFO - 24/08/09 13:27:48 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240809132747-0017/1 on worker-20240809124721-172.18.0.7-36933 (172.18.0.7:36933) with 1 core(s)
[2024-08-09T13:27:48.697+0000] {subprocess.py:93} INFO - 24/08/09 13:27:48 INFO StandaloneSchedulerBackend: Granted executor ID app-20240809132747-0017/1 on hostPort 172.18.0.7:36933 with 1 core(s), 1024.0 MiB RAM
[2024-08-09T13:27:48.869+0000] {subprocess.py:93} INFO - 24/08/09 13:27:48 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240809132747-0017/0 is now RUNNING
[2024-08-09T13:27:48.871+0000] {subprocess.py:93} INFO - 24/08/09 13:27:48 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240809132747-0017/1 is now RUNNING
[2024-08-09T13:27:51.046+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-08-09T13:27:51.046+0000] {subprocess.py:93} INFO -   File "/opt/***/jobs/analyze_data.py", line 47, in <module>
[2024-08-09T13:27:51.047+0000] {subprocess.py:93} INFO -     save_analysis_result(top_gainers, "data/top_gainers.csv")
[2024-08-09T13:27:51.048+0000] {subprocess.py:93} INFO -   File "/opt/***/jobs/analyze_data.py", line 40, in save_analysis_result
[2024-08-09T13:27:51.049+0000] {subprocess.py:93} INFO -     df.coalesce(1).write.mode("overwrite").csv(file_path, header=True)
[2024-08-09T13:27:51.049+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1864, in csv
[2024-08-09T13:27:51.049+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-08-09T13:27:51.050+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2024-08-09T13:27:51.052+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [UNSUPPORTED_DATA_TYPE_FOR_DATASOURCE] The CSV datasource doesn't support the column `_metadata` of the type "MAP<STRING, STRING>".
[2024-08-09T13:27:51.101+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO SparkContext: Invoking stop() from shutdown hook
[2024-08-09T13:27:51.101+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-08-09T13:27:51.107+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO SparkUI: Stopped Spark web UI at http://27ef58cc88fc:4041
[2024-08-09T13:27:51.111+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-08-09T13:27:51.112+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-08-09T13:27:51.138+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-08-09T13:27:51.155+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO MemoryStore: MemoryStore cleared
[2024-08-09T13:27:51.161+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO BlockManager: BlockManager stopped
[2024-08-09T13:27:51.163+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-08-09T13:27:51.165+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-08-09T13:27:51.171+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO SparkContext: Successfully stopped SparkContext
[2024-08-09T13:27:51.171+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO ShutdownHookManager: Shutdown hook called
[2024-08-09T13:27:51.171+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-711086e7-3347-4786-b27f-7365cc3246c8
[2024-08-09T13:27:51.173+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-e443dd6a-aedd-4edd-9c95-c75ed50f593a
[2024-08-09T13:27:51.176+0000] {subprocess.py:93} INFO - 24/08/09 13:27:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-711086e7-3347-4786-b27f-7365cc3246c8/pyspark-e6f4248e-79de-47df-93da-8cc0468640eb
[2024-08-09T13:27:51.205+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-08-09T13:27:51.217+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-08-09T13:27:51.221+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=data_pipeline_api, task_id=analyze_data, execution_date=20240809T132530, start_date=20240809T132740, end_date=20240809T132751
[2024-08-09T13:27:51.229+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task analyze_data (Bash command failed. The command returned a non-zero exit code 1.; 4596)
[2024-08-09T13:27:51.269+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-09T13:27:51.331+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
