[2024-08-14T00:54:29.951+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_api.analyze_data scheduled__2024-08-13T00:30:00+00:00 [queued]>
[2024-08-14T00:54:29.957+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_api.analyze_data scheduled__2024-08-13T00:30:00+00:00 [queued]>
[2024-08-14T00:54:29.957+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-08-14T00:54:29.963+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): analyze_data> on 2024-08-13 00:30:00+00:00
[2024-08-14T00:54:29.968+0000] {standard_task_runner.py:57} INFO - Started process 39500 to run task
[2024-08-14T00:54:29.970+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_api', 'analyze_data', 'scheduled__2024-08-13T00:30:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/spark-jobs.py', '--cfg-path', '/tmp/tmp3rrr5r6c']
[2024-08-14T00:54:29.972+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask analyze_data
[2024-08-14T00:54:30.002+0000] {task_command.py:415} INFO - Running <TaskInstance: data_pipeline_api.analyze_data scheduled__2024-08-13T00:30:00+00:00 [running]> on host 27ef58cc88fc
[2024-08-14T00:54:30.040+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_api' AIRFLOW_CTX_TASK_ID='analyze_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-13T00:30:00+00:00'
[2024-08-14T00:54:30.042+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-14T00:54:30.043+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash /opt/***/jobs/spark-submit.sh /opt/***/jobs/analyze_data.py ']
[2024-08-14T00:54:30.050+0000] {subprocess.py:86} INFO - Output:
[2024-08-14T00:54:30.056+0000] {subprocess.py:93} INFO - /opt/***/jobs/analyze_data.py
[2024-08-14T00:54:30.130+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-08-14T00:54:31.647+0000] {subprocess.py:93} INFO - 24/08/14 00:54:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-14T00:54:32.717+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO SparkContext: Running Spark version 3.5.1
[2024-08-14T00:54:32.720+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO SparkContext: OS info Linux, 6.6.32-linuxkit, aarch64
[2024-08-14T00:54:32.721+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO SparkContext: Java version 11.0.23
[2024-08-14T00:54:32.767+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO ResourceUtils: ==============================================================
[2024-08-14T00:54:32.768+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-08-14T00:54:32.768+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO ResourceUtils: ==============================================================
[2024-08-14T00:54:32.769+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO SparkContext: Submitted application: FinanceDataAnalysis
[2024-08-14T00:54:32.804+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 1024, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-08-14T00:54:32.828+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2024-08-14T00:54:32.834+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-08-14T00:54:32.937+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO SecurityManager: Changing view acls to: ***
[2024-08-14T00:54:32.938+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO SecurityManager: Changing modify acls to: ***
[2024-08-14T00:54:32.939+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO SecurityManager: Changing view acls groups to:
[2024-08-14T00:54:32.939+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO SecurityManager: Changing modify acls groups to:
[2024-08-14T00:54:32.940+0000] {subprocess.py:93} INFO - 24/08/14 00:54:32 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-08-14T00:54:33.227+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO Utils: Successfully started service 'sparkDriver' on port 40583.
[2024-08-14T00:54:33.254+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO SparkEnv: Registering MapOutputTracker
[2024-08-14T00:54:33.287+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO SparkEnv: Registering BlockManagerMaster
[2024-08-14T00:54:33.300+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-08-14T00:54:33.301+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-08-14T00:54:33.303+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-08-14T00:54:33.340+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-6b503e40-9055-438b-b8e4-3b61a9ee801a
[2024-08-14T00:54:33.364+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO MemoryStore: MemoryStore started with capacity 1458.4 MiB
[2024-08-14T00:54:33.380+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-08-14T00:54:33.556+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-08-14T00:54:33.605+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-08-14T00:54:33.625+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2024-08-14T00:54:33.665+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO SparkContext: Added JAR file:///opt/bitnami/spark/resources/elasticsearch-spark-30_2.12-8.4.3.jar at spark://27ef58cc88fc:40583/jars/elasticsearch-spark-30_2.12-8.4.3.jar with timestamp 1723596872706
[2024-08-14T00:54:33.807+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-08-14T00:54:33.895+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.4:7077 after 51 ms (0 ms spent in bootstraps)
[2024-08-14T00:54:33.994+0000] {subprocess.py:93} INFO - 24/08/14 00:54:33 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240814005433-0031
[2024-08-14T00:54:34.022+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42271.
[2024-08-14T00:54:34.023+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO NettyBlockTransferService: Server created on 27ef58cc88fc:42271
[2024-08-14T00:54:34.026+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-08-14T00:54:34.035+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 27ef58cc88fc, 42271, None)
[2024-08-14T00:54:34.052+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO BlockManagerMasterEndpoint: Registering block manager 27ef58cc88fc:42271 with 1458.4 MiB RAM, BlockManagerId(driver, 27ef58cc88fc, 42271, None)
[2024-08-14T00:54:34.064+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 27ef58cc88fc, 42271, None)
[2024-08-14T00:54:34.069+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 27ef58cc88fc, 42271, None)
[2024-08-14T00:54:34.407+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-08-14T00:54:34.800+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-08-14T00:54:34.809+0000] {subprocess.py:93} INFO - 24/08/14 00:54:34 INFO SharedState: Warehouse path is 'file:/tmp/***tmpebzyc7fa/spark-warehouse'.
[2024-08-14T00:54:35.074+0000] {local_task_job_runner.py:274} WARNING - Recorded pid 39704 does not match the current pid 39500
[2024-08-14T00:54:35.085+0000] {process_utils.py:131} INFO - Sending 15 to group 39500. PIDs of all processes in the group: [39504, 39506, 39664, 39500]
[2024-08-14T00:54:35.086+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 39500
[2024-08-14T00:54:35.089+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-14T00:54:35.090+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-08-14T00:54:35.131+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-08-14T00:54:35.146+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=data_pipeline_api, task_id=analyze_data, execution_date=20240813T003000, start_date=20240814T005432, end_date=20240814T005435
[2024-08-14T00:54:35.170+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task analyze_data (Task received SIGTERM signal; 39500)
[2024-08-14T00:54:35.357+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=39504, status='terminated', started='00:54:30') (39504) terminated with exit code None
[2024-08-14T00:54:35.359+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=39664, status='terminated', started='00:54:31') (39664) terminated with exit code None
[2024-08-14T00:54:35.361+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=39500, status='terminated', exitcode=1, started='00:54:29') (39500) terminated with exit code 1
[2024-08-14T00:54:35.459+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=39506, status='terminated', started='00:54:30') (39506) terminated with exit code None
