[2024-08-08T09:27:46.028+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.process_data scheduled__2024-08-07T00:30:00+00:00 [queued]>
[2024-08-08T09:27:46.031+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.process_data scheduled__2024-08-07T00:30:00+00:00 [queued]>
[2024-08-08T09:27:46.031+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-08-08T09:27:46.035+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_data> on 2024-08-07 00:30:00+00:00
[2024-08-08T09:27:46.038+0000] {standard_task_runner.py:57} INFO - Started process 1114 to run task
[2024-08-08T09:27:46.039+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'process_data', 'scheduled__2024-08-07T00:30:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/spark-jobs.py', '--cfg-path', '/tmp/tmpng73s_bw']
[2024-08-08T09:27:46.042+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask process_data
[2024-08-08T09:27:46.073+0000] {task_command.py:415} INFO - Running <TaskInstance: data_pipeline.process_data scheduled__2024-08-07T00:30:00+00:00 [running]> on host c553c98b8e80
[2024-08-08T09:27:46.100+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-07T00:30:00+00:00'
[2024-08-08T09:27:46.100+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-08T09:27:46.101+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/jobs/process_data.py ']
[2024-08-08T09:27:46.105+0000] {subprocess.py:86} INFO - Output:
[2024-08-08T09:27:46.507+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-08-08T09:27:47.816+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2024-08-08T09:27:47.817+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2024-08-08T09:27:48.000+0000] {subprocess.py:93} INFO - 24/08/08 09:27:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-08T09:27:49.349+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-08-08T09:27:49.350+0000] {subprocess.py:93} INFO -   File "/opt/***/jobs/process_data.py", line 51, in <module>
[2024-08-08T09:27:49.350+0000] {subprocess.py:93} INFO -     market_trends = load_data(spark, "data/market_trends.json")
[2024-08-08T09:27:49.350+0000] {subprocess.py:93} INFO -                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-08T09:27:49.350+0000] {subprocess.py:93} INFO -   File "/opt/***/jobs/process_data.py", line 6, in load_data
[2024-08-08T09:27:49.350+0000] {subprocess.py:93} INFO -     return spark.read.json(file_path)
[2024-08-08T09:27:49.350+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-08T09:27:49.350+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/sql/readwriter.py", line 425, in json
[2024-08-08T09:27:49.350+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.json(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2024-08-08T09:27:49.351+0000] {subprocess.py:93} INFO -                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-08-08T09:27:49.351+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-08-08T09:27:49.351+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2024-08-08T09:27:49.351+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^
[2024-08-08T09:27:49.351+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
[2024-08-08T09:27:49.351+0000] {subprocess.py:93} INFO -     raise converted from None
[2024-08-08T09:27:49.354+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpnfx804h0/data/market_trends.json.
[2024-08-08T09:27:49.823+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-08-08T09:27:49.837+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-08-08T09:27:49.841+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=process_data, execution_date=20240807T003000, start_date=20240808T092746, end_date=20240808T092749
[2024-08-08T09:27:49.849+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 86 for task process_data (Bash command failed. The command returned a non-zero exit code 1.; 1114)
[2024-08-08T09:27:49.881+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-08T09:27:49.899+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
